-- MySQL Script generated by MySQL Workbench
-- 07/31/17 14:33:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema school
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `school` ;

-- -----------------------------------------------------
-- Schema school
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `school` DEFAULT CHARACTER SET utf8 ;
USE `school` ;

-- -----------------------------------------------------
-- Table `school`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`user` ;

CREATE TABLE IF NOT EXISTS `school`.`user` (
  `iduser` BIGINT NOT NULL AUTO_INCREMENT,
  `tel` VARCHAR(11) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `nickname` VARCHAR(64) NOT NULL,
  `jobtitle` VARCHAR(128) NOT NULL,
  `headportrait` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`iduser`, `tel`),
  UNIQUE INDEX `iduser_UNIQUE` (`iduser` ASC),
  UNIQUE INDEX `tel_UNIQUE` (`tel` ASC),
  UNIQUE INDEX `nickname_UNIQUE` (`nickname` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `school`.`jobinfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`jobinfo` ;

CREATE TABLE IF NOT EXISTS `school`.`jobinfo` (
  `idjobinfo` BIGINT NOT NULL AUTO_INCREMENT,
  `user_iduser` BIGINT NOT NULL,
  `post` VARCHAR(128) NOT NULL,
  `company` VARCHAR(256) NOT NULL,
  `money` VARCHAR(256) NOT NULL,
  `workingplace` VARCHAR(256) NOT NULL,
  `jobcontent` TEXT NOT NULL,
  `workhour` VARCHAR(128) NOT NULL,
  `time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idjobinfo`, `user_iduser`),
  INDEX `fk_jobinfo_user_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_jobinfo_user`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `school`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `school`.`school`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`school` ;

CREATE TABLE IF NOT EXISTS `school`.`school` (
  `idschool` INT NOT NULL AUTO_INCREMENT,
  `schoolname` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`idschool`),
  UNIQUE INDEX `schoolname_UNIQUE` (`schoolname` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`lostandfound`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`lostandfound` ;

CREATE TABLE IF NOT EXISTS `school`.`lostandfound` (
  `idLostandFound` BIGINT NOT NULL AUTO_INCREMENT,
  `user_iduser` BIGINT NOT NULL,
  `school_idschool` INT NOT NULL,
  `itemtype` VARCHAR(256) NOT NULL,
  `description` TEXT NOT NULL,
  `contactinformation` VARCHAR(256) NOT NULL,
  `pic` VARCHAR(256) NOT NULL,
  `time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idLostandFound`, `user_iduser`, `school_idschool`),
  INDEX `fk_LostandFound_user1_idx` (`user_iduser` ASC),
  INDEX `fk_LostandFound_school1_idx` (`school_idschool` ASC),
  CONSTRAINT `fk_LostandFound_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `school`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LostandFound_school1`
    FOREIGN KEY (`school_idschool`)
    REFERENCES `school`.`school` (`idschool`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`concern`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`concern` ;

CREATE TABLE IF NOT EXISTS `school`.`concern` (
  `idconcern` BIGINT NOT NULL AUTO_INCREMENT,
  `user1` BIGINT NOT NULL,
  `user2` BIGINT NOT NULL,
  PRIMARY KEY (`idconcern`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`postgraduate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`postgraduate` ;

CREATE TABLE IF NOT EXISTS `school`.`postgraduate` (
  `idpostgraduate` BIGINT NOT NULL AUTO_INCREMENT,
  `user_iduser` BIGINT NOT NULL,
  `content` TEXT NOT NULL,
  `pic` TEXT NOT NULL,
  `time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idpostgraduate`, `user_iduser`),
  INDEX `fk_postgraduate_user1_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_postgraduate_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `school`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`comment` ;

CREATE TABLE IF NOT EXISTS `school`.`comment` (
  `idcomment` BIGINT NOT NULL AUTO_INCREMENT,
  `user_iduser` BIGINT NOT NULL,
  `post_id` BIGINT NOT NULL,
  `type` INT NOT NULL,
  `content` TEXT NOT NULL,
  `time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idcomment`, `user_iduser`),
  INDEX `fk_comment_user1_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `school`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`collection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`collection` ;

CREATE TABLE IF NOT EXISTS `school`.`collection` (
  `idcollection` INT NOT NULL AUTO_INCREMENT,
  `user_iduser` BIGINT NOT NULL,
  `type` INT NOT NULL,
  `post_id` BIGINT NOT NULL,
  PRIMARY KEY (`idcollection`, `user_iduser`),
  INDEX `fk_collection_user1_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_collection_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `school`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
